packages:
  - 'e2e-tests'
allowBuilds:
  edgedriver: true
  esbuild: true
  geckodriver: true
patchedDependencies:
  '@plait-board/react-board@0.4.0-0': patches/@plait-board__react-board@0.4.0-0.patch
  '@plait/common@0.93.1': patches/@plait__common@0.93.1.patch
  '@plait/core@0.93.1': patches/@plait__core@0.93.1.patch
  '@plait/draw@0.93.1': patches/@plait__draw@0.93.1.patch
  '@plait/mind@0.93.1': patches/@plait__mind@0.93.1.patch
