//! Native PDF export: convert a single Markdown file to PDF using IronPress.
//!
//! IronPress is a pure-Rust HTML/CSS/Markdown→PDF converter with a built-in
//! layout engine (flexbox, grid, @page, @font-face). Unlike genpdf-chinese
//! (the previous engine — unmaintained, no CSS, manual element rendering),
//! IronPress handles CSS layout natively, producing high-quality output
//! comparable to browser-based rendering.
//!
//! CJK text is shaped via HarfBuzz (rustybuzz) with automatic Unicode font
//! fallback — no manual font registration needed. Images (PNG/JPEG/SVG) are
//! embedded as data URIs in the HTML, which IronPress renders directly.

use std::fs;
use std::path::Path;

use ironpress::{HtmlConverter, Margin, PageSize};

use super::export;

// ═══════════════════════════════════════════════════════════════
// Public API
// ═══════════════════════════════════════════════════════════════

/// Export a single Markdown file as a PDF document.
///
/// The Markdown is converted to styled HTML (with embedded images and CSS)
/// via `export::export_pdf_file_html`, then rendered to PDF by IronPress's
/// built-in layout engine.
pub fn export_file_as_pdf(
    workspace_path: &Path,
    file_path: &str,
    output_path: &Path,
    title_override: Option<&str>,
    author_override: Option<&str>,
) -> Result<(), String> {
    // 1. Generate styled HTML with embedded data-URI images
    let html = export::export_pdf_file_html(
        workspace_path,
        file_path,
        title_override,
        author_override,
    )?;

    // 2. Convert HTML → PDF via IronPress
    //
    // IronPress discovers system fonts automatically (fontdb), so CJK text
    // works out-of-the-box on any system with CJK fonts installed. We
    // disable HTML sanitization because the HTML is generated by our own
    // trusted md_to_html pipeline — it contains no <script> or event
    // handlers, and sanitization would strip the <style> block we need.
    let pdf_bytes = HtmlConverter::new()
        .page_size(PageSize::A4)
        .margin(Margin::uniform(56.7)) // ~2cm at 72dpi
        .sanitize(false)
        .convert(&html)
        .map_err(|e| format!("PDF 生成失败：{e}"))?;

    // 3. Write output
    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("创建输出目录失败：{e}"))?;
    }
    fs::write(output_path, &pdf_bytes)
        .map_err(|e| format!("写入 PDF 失败：{e}"))?;

    Ok(())
}

// ═══════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;
    use crate::services::workspace;
    use tempfile::TempDir;

    fn setup_test_workspace(dir: &Path) {
        workspace::create_workspace(dir, "测试文档", "测试作者", Some("zh-CN")).unwrap();
        let ch1 = dir.join("01-intro");
        fs::create_dir_all(ch1.join("assets")).unwrap();
        fs::write(ch1.join("index.md"), "# 入门指南\n\n欢迎使用本书。\n").unwrap();
        let summary = "# 测试文档\n- [入门指南](01-intro/index.md)\n";
        fs::write(dir.join("SUMMARY.md"), summary).unwrap();
    }

    fn assert_valid_pdf(path: &Path) {
        assert!(path.exists(), "PDF file should exist");
        let data = fs::read(path).unwrap();
        assert!(data.starts_with(b"%PDF-"), "Output should be a valid PDF");
        assert!(data.len() > 500, "PDF should be non-trivial, got {} bytes", data.len());
    }

    /// Assert that a generated PDF actually embeds an image (contains an image
    /// XObject resource). This guards against regressions where the layout
    /// engine silently drops `<img>` elements (e.g. when nested in `<p>`).
    fn assert_pdf_contains_image(path: &Path) {
        let data = fs::read(path).unwrap();
        let s = String::from_utf8_lossy(&data);
        assert!(
            s.contains("/Image") || s.contains("/XObject"),
            "PDF should embed at least one image XObject, but none found ({} bytes)",
            data.len()
        );
    }

    #[test]
    fn export_file_as_pdf_basic_markdown() {
        let tmp = TempDir::new().unwrap();
        let ws = tmp.path().join("ws");
        setup_test_workspace(&ws);
        let out = tmp.path().join("output.pdf");
        let result = export_file_as_pdf(&ws, "01-intro/index.md", &out, None, None);
        assert!(result.is_ok(), "export failed: {:?}", result);
        assert_valid_pdf(&out);
    }

    #[test]
    fn export_file_as_pdf_rich_content() {
        let tmp = TempDir::new().unwrap();
        let ws = tmp.path().join("ws");
        setup_test_workspace(&ws);
        let md = "# 主标题\n\n## 二级标题\n\n正文，包含**粗体**和*斜体*。\n\n### 三级标题\n\n- 项目一\n- 项目二\n\n```\nlet x = 1;\n```\n\n| A | B |\n|---|---|\n| 1 | 2 |\n";
        fs::write(ws.join("rich.md"), md).unwrap();
        let out = tmp.path().join("output.pdf");
        let result = export_file_as_pdf(&ws, "rich.md", &out, None, None);
        assert!(result.is_ok(), "export failed: {:?}", result);
        assert_valid_pdf(&out);
    }

    #[test]
    fn export_file_as_pdf_chinese_text() {
        let tmp = TempDir::new().unwrap();
        let ws = tmp.path().join("ws");
        setup_test_workspace(&ws);
        let md = "# 中文测试\n\n这是一段中文文字。\n\n包含**粗体中文**和*斜体中文*。\n\n- 列表项目一\n- 列表项目二\n";
        fs::write(ws.join("chinese.md"), md).unwrap();
        let out = tmp.path().join("output.pdf");
        let result = export_file_as_pdf(&ws, "chinese.md", &out, None, None);
        assert!(result.is_ok(), "export failed: {:?}", result);
        assert_valid_pdf(&out);
    }

    #[test]
    fn export_file_as_pdf_missing_file() {
        let tmp = TempDir::new().unwrap();
        let ws = tmp.path().join("ws");
        setup_test_workspace(&ws);
        let out = tmp.path().join("output.pdf");
        let result = export_file_as_pdf(&ws, "nonexistent.md", &out, None, None);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("不存在"));
    }

    #[test]
    fn export_file_as_pdf_with_title_override() {
        let tmp = TempDir::new().unwrap();
        let ws = tmp.path().join("ws");
        setup_test_workspace(&ws);
        let out = tmp.path().join("output.pdf");
        let result = export_file_as_pdf(&ws, "01-intro/index.md", &out, Some("自定义标题"), None);
        assert!(result.is_ok(), "export failed: {:?}", result);
        assert_valid_pdf(&out);
    }

    // ── Extended tests for cross-platform verification ──

    #[test]
    fn export_file_as_pdf_tables() {
        let tmp = TempDir::new().unwrap();
        let ws = tmp.path().join("ws");
        setup_test_workspace(&ws);
        let md = "# 表格测试\n\n| 列A | 列B | 列C |\n|-----|-----|-----|\n| 数据1 | 数据2 | 数据3 |\n| 中文1 | 中文2 | 中文3 |\n\n多列表格导出。\n";
        fs::write(ws.join("tables.md"), md).unwrap();
        let out = tmp.path().join("output.pdf");
        let result = export_file_as_pdf(&ws, "tables.md", &out, None, None);
        assert!(result.is_ok(), "export failed: {:?}", result);
        assert_valid_pdf(&out);
    }

    #[test]
    fn export_file_as_pdf_task_list() {
        let tmp = TempDir::new().unwrap();
        let ws = tmp.path().join("ws");
        setup_test_workspace(&ws);
        let md = "# 任务列表\n\n- [x] 已完成任务\n- [ ] 未完成任务\n- [x] 另一个完成项\n\n普通文本。\n";
        fs::write(ws.join("tasks.md"), md).unwrap();
        let out = tmp.path().join("output.pdf");
        let result = export_file_as_pdf(&ws, "tasks.md", &out, None, None);
        assert!(result.is_ok(), "export failed: {:?}", result);
        assert_valid_pdf(&out);
    }

    #[test]
    fn export_file_as_pdf_mixed_heading_levels() {
        let tmp = TempDir::new().unwrap();
        let ws = tmp.path().join("ws");
        setup_test_workspace(&ws);
        let md = "# H1 标题\n\n## H2 标题\n\n### H3 标题\n\n#### H4 标题\n\n##### H5 标题\n\n各层级标题正文。\n";
        fs::write(ws.join("headings.md"), md).unwrap();
        let out = tmp.path().join("output.pdf");
        let result = export_file_as_pdf(&ws, "headings.md", &out, None, None);
        assert!(result.is_ok(), "export failed: {:?}", result);
        assert_valid_pdf(&out);
    }

    #[test]
    fn export_file_as_pdf_code_block_with_language() {
        let tmp = TempDir::new().unwrap();
        let ws = tmp.path().join("ws");
        setup_test_workspace(&ws);
        let md = "# 代码块测试\n\n```rust\nfn main() {\n    println!(\"Hello, 世界！\");\n}\n```\n\n```javascript\nconst x = 42;\nconsole.log(x);\n```\n";
        fs::write(ws.join("code.md"), md).unwrap();
        let out = tmp.path().join("output.pdf");
        let result = export_file_as_pdf(&ws, "code.md", &out, None, None);
        assert!(result.is_ok(), "export failed: {:?}", result);
        assert_valid_pdf(&out);
    }

    #[test]
    fn export_file_as_pdf_inline_code() {
        let tmp = TempDir::new().unwrap();
        let ws = tmp.path().join("ws");
        setup_test_workspace(&ws);
        let md = "# 行内代码\n\n使用 `cargo test` 运行测试。`Rust` 是一门系统编程语言。\n";
        fs::write(ws.join("inline-code.md"), md).unwrap();
        let out = tmp.path().join("output.pdf");
        let result = export_file_as_pdf(&ws, "inline-code.md", &out, None, None);
        assert!(result.is_ok(), "export failed: {:?}", result);
        assert_valid_pdf(&out);
    }

    #[test]
    fn export_file_as_pdf_strikethrough() {
        let tmp = TempDir::new().unwrap();
        let ws = tmp.path().join("ws");
        setup_test_workspace(&ws);
        let md = "# 删除线\n\n~~这段文字被删除了~~\n\n正常文本和~~删除~~混排。\n";
        fs::write(ws.join("strike.md"), md).unwrap();
        let out = tmp.path().join("output.pdf");
        let result = export_file_as_pdf(&ws, "strike.md", &out, None, None);
        assert!(result.is_ok(), "export failed: {:?}", result);
        assert_valid_pdf(&out);
    }

    #[test]
    fn export_file_as_pdf_horizontal_rule() {
        let tmp = TempDir::new().unwrap();
        let ws = tmp.path().join("ws");
        setup_test_workspace(&ws);
        let md = "# 分隔线\n\n上部分内容\n\n---\n\n下部分内容\n";
        fs::write(ws.join("rule.md"), md).unwrap();
        let out = tmp.path().join("output.pdf");
        let result = export_file_as_pdf(&ws, "rule.md", &out, None, None);
        assert!(result.is_ok(), "export failed: {:?}", result);
        assert_valid_pdf(&out);
    }

    #[test]
    fn export_file_as_pdf_embedded_png_image() {
        let tmp = TempDir::new().unwrap();
        let ws = tmp.path().join("ws");
        setup_test_workspace(&ws);
        // Create a small PNG image (1x1 red pixel)
        let assets_dir = ws.join("assets");
        fs::create_dir_all(&assets_dir).unwrap();
        // Minimal valid PNG: 1x1 red pixel
        let png_bytes: [u8; 69] = [
            0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, // PNG signature
            0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52, // IHDR chunk
            0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, // 1x1
            0x08, 0x02, 0x00, 0x00, 0x00, 0x90, 0x77, 0x53, // 8-bit RGB
            0xDE, 0x00, 0x00, 0x00, 0x0C, 0x49, 0x44, 0x41, // IDAT chunk
            0x54, 0x08, 0xD7, 0x63, 0xF8, 0xCF, 0xC0, 0x00, // compressed data
            0x00, 0x00, 0x02, 0x00, 0x01, 0xE2, 0x21, 0xBC, // CRC
            0x33, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, // IEND chunk
            0x44, 0xAE, 0x42, 0x60, 0x82,                     // CRC
        ];
        fs::write(assets_dir.join("test.png"), png_bytes).unwrap();
        let md = "# 图片测试\n\n![测试图片](assets/test.png)\n\n图片后文本。\n";
        fs::write(ws.join("image.md"), md).unwrap();
        let out = tmp.path().join("output.pdf");
        let result = export_file_as_pdf(&ws, "image.md", &out, None, None);
        assert!(result.is_ok(), "export failed: {:?}", result);
        assert_valid_pdf(&out);
        // Regression: pulldown-cmark wraps <img> in <p>, so the image must
        // actually be embedded in the PDF (not silently dropped).
        assert_pdf_contains_image(&out);
    }

    /// Regression test for the whiteboard image flow.
    ///
    /// Whiteboards save images as SVG files referenced via relative paths
    /// `./assets/<doc>-img-<NNN>.svg` (see buildMarkdownRef in
    /// whiteboardService.ts). pulldown-cmark wraps the resulting `<img>` in a
    /// `<p>`, which — before the IronPress layout patch — caused the image to
    /// be silently dropped during text-run collection. This test ensures the
    /// SVG→PNG conversion succeeds and the image is embedded in the PDF.
    #[test]
    fn export_file_as_pdf_whiteboard_svg_image() {
        let tmp = TempDir::new().unwrap();
        let ws = tmp.path().join("ws");
        setup_test_workspace(&ws);

        // Chapter directory with an assets/ subdir holding an SVG image.
        let ch = ws.join("ch1");
        let assets = ch.join("assets");
        fs::create_dir_all(&assets).unwrap();
        let svg = r##"<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="200" height="100" viewBox="0 0 200 100">
  <rect x="0" y="0" width="200" height="100" fill="#ff0000"/>
  <rect x="10" y="10" width="80" height="80" fill="#0000ff"/>
</svg>"##;
        fs::write(assets.join("doc-img-001.svg"), svg).unwrap();

        // Markdown references the SVG exactly like the whiteboard does.
        let md = "# 白板图\n\n![img-001](./assets/doc-img-001.svg)\n\n文字。\n";
        fs::write(ch.join("index.md"), md).unwrap();

        // Verify SVG→PNG conversion succeeds.
        let svg_bytes = fs::read(assets.join("doc-img-001.svg")).unwrap();
        assert!(super::export::svg_to_png_bytes(&svg_bytes).is_some(), "SVG→PNG conversion should succeed");

        // Verify the generated HTML embeds the image as a data URI.
        let html = super::export::export_pdf_file_html(&ws, "ch1/index.md", None, None).unwrap();
        assert!(html.contains("data:image/png;base64,"), "HTML should embed converted PNG as data URI");

        // Verify the PDF actually contains the image.
        let out = tmp.path().join("output.pdf");
        export_file_as_pdf(&ws, "ch1/index.md", &out, None, None).unwrap();
        assert_valid_pdf(&out);
        assert_pdf_contains_image(&out);
    }

    #[test]
    fn export_file_as_pdf_long_document() {
        let tmp = TempDir::new().unwrap();
        let ws = tmp.path().join("ws");
        setup_test_workspace(&ws);
        // Generate a multi-page document
        let mut md = String::from("# 长文档测试\n\n");
        for i in 1..=50 {
            md.push_str(&format!("## 第 {} 节\n\n这是第 {} 节的内容。包含一些中文文字和 English text。\n\n", i, i));
            if i % 5 == 0 {
                md.push_str(&format!("```\nfn function_{}() {{\n    let x = {};\n}}\n```\n\n", i, i));
            }
        }
        fs::write(ws.join("long.md"), md).unwrap();
        let out = tmp.path().join("output.pdf");
        let result = export_file_as_pdf(&ws, "long.md", &out, None, None);
        assert!(result.is_ok(), "export failed: {:?}", result);
        assert_valid_pdf(&out);
        // Long document should produce a substantial PDF
        let data = fs::read(&out).unwrap();
        assert!(data.len() > 5000, "Long document PDF should be substantial, got {} bytes", data.len());
    }
}
